name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Déclenche le déploiement quand tu push sur main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist      # Le dossier généré par Vite
          branch: gh-pages  # La branche où le site sera hébergé